name: Ubuntu
on:
  workflow_dispatch:

jobs:
  secure-ssh:
    runs-on: ubuntu-latest
    timeout-minutes: 3600
    env:
      DEBIAN_FRONTEND: noninteractive
      DEBIAN_PRIORITY: critical
      TZ: Asia/Shanghai
      
    steps:     
      - name: 更改系统语言(中文)
        run: |
          sudo -i <<EOF
          apt update -y
          apt install -y locales language-pack-zh-hans language-pack-zh-hans-base
          locale-gen zh_CN.UTF-8
          update-locale LANG=zh_CN.UTF-8 LC_ALL=zh_CN.UTF-8
          EOF
          
      - name: 关闭防火墙
        run: |
          sudo -i <<EOF
          ufw disable
          EOF

      - name: 安装Tailscale和VS Code网页版
        run: |
          sudo -i <<EOF
          curl -fsSL https://tailscale.com/install.sh | sh
          curl -fsSL https://code-server.dev/install.sh | sh

      - name: 连接Tailscale内网
        env:
          KEY: ${{ secrets.KEY }}
        run: |
          sudo tailscale up --authkey "$KEY" --hostname "github-${{ github.run_id }}"
          TAILSCALE_IP=""
          RETRIES=0
          while [ -z "$TAILSCALE_IP" ] && [ $RETRIES -lt 10 ]; do
            TAILSCALE_IP=$(sudo tailscale ip -4)
            sleep 3
            RETRIES=$((RETRIES + 1))
          done
          if [ -z "$TAILSCALE_IP" ]; then
            echo "Error: Failed to get Tailscale IPv4 address."
            exit 1
          fi
          echo "TAILSCALE_IP=$TAILSCALE_IP" >> $GITHUB_ENV

      - name: 配置VS Code网页版
        run: |
          systemctl stop code-server@* 2>/dev/null
          systemctl disable code-server@* 2>/dev/null
          code-server --bind-addr 127.0.0.1:8080 &
          sleep 10
          pkill -f code-server
          sed -i '
          s/bind-addr: 127.0.0.1:8080/bind-addr: 0.0.0.0:8080/
          s/auth: password/auth: none/
          ' ~/.config/code-server/config.yaml
          systemctl enable --now code-server@runner
          EOF


      - name: 展示信息
        run: |
          echo "======================================"
          echo "SSH远程连接信息"
          echo "======================================"
          echo "Tailscale内网IP: ${{ env.TAILSCALE_IP }}"
          echo "VS Code网页版IP: ${{ env.TAILSCALE_IP }}:8080"
          echo "======================================"
      
      - name: 持续保活
        run: |
          while true; do
            echo "Ubuntu服务器运行中"
            sleep 300
          done